project:
  name: go-lucky
  binary: go-lucky
  module: github.com/mrz1836/go-lucky
  main: ./cmd/go-lucky/main.go

build:
  # Custom ldflags with version injection
  ldflags:
    - "-s -w"
    - "-X main.version={{.Version}}"
    - "-X main.commit={{.Commit}}"
    - "-X main.buildDate={{.Date}}"
  flags:
    - "-trimpath"
  output: "./bin/go-lucky"
